### PR TITLE
fix: update the school name picture

### PR DESCRIPTION
**Pull request by strear**
The picture of Tongji name is replaced with a vector image from the [official website](http://xxgk.tongji.edu.cn/index.php?classid=3080&newsid=6828&t=show). The current one is crooked...

### CODE REVIEW

**Comment by ganler** [comment]
@strear Thank you for your contribution! If you have time, you might also want to consider updating the overleaf link.

**Comment by strear** [comment]
> @strear Thank you for your contribution! If you have time, you might also want to consider updating the overleaf link.

我试着在 Overleaf 上提交了模板，但是审核人员退回了，理由是不同账号提交的模板不能同名或相互替换。所以这个可能还是需要学长处理一下了……

另外，SJTUG 的 LaTeX 学位论文模板 [sjtug/SJTUThesis](https://github.com/sjtug/SJTUThesis) 现在已经非常完善了，也许将来有时间的时候我可以做一个 CI 脚本，把那边的改进同步过来，自动替换校名和校徽等信息。这样的话，就可以把这里 [tongji-common-thesis](https://github.com/TJ-CSCCG/tongji-common-thesis) 的功能也整合进来了。但这可能需要先询问一下对方的维护者，也有一些额外的工作，所以希望可以有机会完成这件事吧。

**Comment by ganler** [comment]
I see. I will update it later. It would be super appreciated if you have time to contribute other things including CI. If you want help from SJTUG community, you might want to contact @skyzh

**Comment by skyzh** [comment]
Glad to help!

**Pull request merged**
